version: "3.7"
services:
  app:
    container_name: ${PROJECT_NAME}_app
    image: node:14.17
    working_dir: /app
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./app/:/app
    command: bash -c "npm i && npm run start:dev"
    restart: always
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
  redis:
    container_name: ${PROJECT_NAME}_redis
    image: bitnami/redis:latest
    volumes:
      - storage:/data/redis
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    networks:
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
networks:
  backend:
    driver: bridge
volumes:
  storage:
